apiVersion: v1
kind: Service
metadata:
  name: greeter-server
  namespace: kks-backyard-stage
spec:
  ports:
  # Use port name in "<protocol>[-<suffix>]" format, otherwise traffic
  # coming from appmesh nodes will silently ignore appmesh RouteRules.
  - name: grpc
    port: 50051
  selector:
    app: greeter-server

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: greeter-server-deployment
  namespace: kks-backyard-stage
spec:
  replicas: 3
  selector:
    matchLabels:
      app: greeter-server
  template:
    metadata:
      labels:
        app: greeter-server
    spec:
      containers:
      - name: greeter-server
        image: 038528481894.dkr.ecr.ap-northeast-1.amazonaws.com/greeter_server:v6
        imagePullPolicy: Always 
        ports:
        - containerPort: 50051
        env:
        - name: GRPC_VERBOSITY
          value: "debug"
        - name: MY_POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
