apiVersion: v1
kind: Service
metadata:
  name: greeter-client
  namespace: kks-backyard-stage
spec:
  ports:
  # Use port name in "<protocol>[-<suffix>]" format, otherwise traffic
  # coming from appmesh nodes will silently ignore appmesh RouteRules.
  - name: grpc
    port: 8080
  selector:
    app: greeter-client

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: greeter-client
  namespace: kks-backyard-stage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: greeter-client
  template:
    metadata:
      labels:
        app: greeter-client
    spec:
      containers:
      - name: greeter-client
        image: 038528481894.dkr.ecr.ap-northeast-1.amazonaws.com/greeter_client:v2
        ports:
        - containerPort: 8080
        env:
        # Resolve backend IP using cluster-internal DNS name of the backend service
        - name: GREETER_SERVICE_TARGET
          value: "greeter-server.kks-backyard-stage.svc.cluster.local:50051"
        - name: GRPC_VERBOSITY
          value: "debug"
        #- name: GRPC_TRACE
        #  value: "tcp,http"
